USE `full-stack-ecommerce`;

DROP TABLE IF EXISTS `state`;
DROP TABLE IF EXISTS `country`;

CREATE TABLE `country` (
  `id` smallint unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(2) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE `state` (
  `id` smallint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `country_id` smallint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_country` (`country_id`),
  CONSTRAINT `fk_country_id` FOREIGN KEY (`country_id`) REFERENCES `country`(`id`)
) ENGINE=InnoDB;

INSERT INTO `country` (`code`, `name`) VALUES ('BR', 'Brazil');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Acre', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Alagoas', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Amapá', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Amazonas', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Bahia', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Ceará', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Distrito Federal', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Espírito Santo', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Goiás', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Maranhão', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Mato Grosso', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Mato Grosso do Sul', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Minas Gerais', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Pará', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Paraíba', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Paraná', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Pernambuco', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Piauí', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Rio de Janeiro', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Rio Grande do Norte', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Rio Grande do Sul', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Rondônia', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Roraima', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Santa Catarina', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('São Paulo', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Sergipe', 1);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tocantins', 1);
INSERT INTO `country` (`code`, `name`) VALUES ('CA', 'Canada');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Alberta', 2);
INSERT INTO `state` (`name`, `country_id`) VALUES ('British Columbia', 2);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Manitoba', 2);
INSERT INTO `state` (`name`, `country_id`) VALUES ('New Brunswick', 2);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Newfoundland and Labrador', 2);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Nova Scotia', 2);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Ontario', 2);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Prince Edward Island', 2);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Quebec', 2);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Saskatchewan', 2);
INSERT INTO `country` (`code`, `name`) VALUES ('DE', 'Germany');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Baden-Württemberg', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Bavaria', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Berlin', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Brandenburg', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Bremen', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hamburg', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hesse', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Lower Saxony', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Mecklenburg-Vorpommern', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('North Rhine-Westphalia', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Rhineland-Palatinate', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Saarland', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Saxony', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Saxony-Anhalt', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Schleswig-Holstein', 3);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Thuringia', 3);
INSERT INTO `country` (`code`, `name`) VALUES ('JP', 'Japan');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Aichi', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Akita', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Aomori', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Chiba', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Ehime', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Fukui', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Fukuoka', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Fukushima', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Gifu', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Gunma', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hiroshima', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hokkaido', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hyogo', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Ibaraki', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Ishikawa', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Iwate', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kagawa', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kagoshima', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kanagawa', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kochi', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kumamoto', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kyoto', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Mie', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Miyagi', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Miyazaki', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Nagano', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Nagasaki', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Nara', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Niigata', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Oita', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Okayama', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Okinawa', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Osaka', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Saga', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Saitama', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Shiga', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Shimane', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Shizuoka', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tochigi', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tokushima', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tokyo', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tottori', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Toyama', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Wakayama', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Yamagata', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Yamaguchi', 4);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Yamanashi', 4);
INSERT INTO `country` (`code`, `name`) VALUES ('SE', 'Sweden');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Blekinge', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Dalarna', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Gävleborg', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Gotland', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Halland', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Jämtland', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Jönköping', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kalmar', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kronoberg', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Norrbotten', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Örebro', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Östergötland', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Skåne', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Södermanland', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Stockholm', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Uppsala', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Värmland', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Västerbotten', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Västernorrland', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Västmanland', 5);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Västra Götaland', 5);
INSERT INTO `country` (`code`, `name`) VALUES ('MX', 'Mexico');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Aguascalientes', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Baja California', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Baja California Sur', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Campeche', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Chiapas', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Chihuahua', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Coahuila', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Colima', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Durango', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Guanajuato', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Guerrero', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hidalgo', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Jalisco', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('México', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Michoacán', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Morelos', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Nayarit', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Nuevo León', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Oaxaca', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Puebla', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Querétaro', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Quintana Roo', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('San Luis Potosí', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Sinaloa', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Sonora', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tabasco', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tamaulipas', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tlaxcala', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Veracruz', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Yucatán', 6);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Zacatecas', 6);
INSERT INTO `country` (`code`, `name`) VALUES ('KR', 'South Korea');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Busan', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Chungcheongbuk-do', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Chungcheongnam-do', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Daegu', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Daejeon', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Gangwon-do', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Gwangju', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Gyeonggi-do', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Gyeongsangbuk-do', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Gyeongsangnam-do', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Incheon', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Jeju-do', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Jeollabuk-do', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Jeollanam-do', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Sejong', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Seoul', 7);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Ulsan', 7);
INSERT INTO `country` (`code`, `name`) VALUES ('CN', 'China');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Anhui', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Beijing', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Chongqing', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Fujian', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Gansu', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Guangdong', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Guangxi', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Guizhou', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hainan', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hebei', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Heilongjiang', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Henan', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hong Kong', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hubei', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hunan', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Inner Mongolia', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Jiangsu', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Jiangxi', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Jilin', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Liaoning', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Macau', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Ningxia', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Qinghai', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Shaanxi', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Shandong', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Shanghai', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Shanxi', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Sichuan', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tianjin', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tibet', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Xinjiang', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Yunnan', 8);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Zhejiang', 8);
INSERT INTO `country` (`code`, `name`) VALUES ('MY', 'Malaysia');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Johor', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kedah', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kelantan', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kuala Lumpur', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Labuan', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Melaka', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Negeri Sembilan', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Pahang', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Penang', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Perak', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Perlis', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Putrajaya', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Sabah', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Sarawak', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Selangor', 9);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Terengganu', 9);
INSERT INTO `country` (`code`, `name`) VALUES ('SG', 'Singapore');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Central Region', 10);
INSERT INTO `state` (`name`, `country_id`) VALUES ('East Region', 10);
INSERT INTO `state` (`name`, `country_id`) VALUES ('North Region', 10);
INSERT INTO `state` (`name`, `country_id`) VALUES ('North-East Region', 10);
INSERT INTO `state` (`name`, `country_id`) VALUES ('West Region', 10);
INSERT INTO `country` (`code`, `name`) VALUES ('US', 'United States');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Alabama', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Alaska', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Arizona', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Arkansas', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('California', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Colorado', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Connecticut', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Delaware', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Florida', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Georgia', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Hawaii', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Idaho', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Illinois', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Indiana', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Iowa', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kansas', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Kentucky', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Louisiana', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Maine', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Maryland', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Massachusetts', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Michigan', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Minnesota', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Mississippi', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Missouri', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Montana', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Nebraska', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Nevada', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('New Hampshire', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('New Jersey', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('New Mexico', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('New York', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('North Carolina', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('North Dakota', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Ohio', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Oklahoma', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Oregon', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Pennsylvania', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Rhode Island', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('South Carolina', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('South Dakota', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tennessee', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Texas', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Utah', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Vermont', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Virginia', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Washington', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('West Virginia', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Wisconsin', 11);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Wyoming', 11);
INSERT INTO `country` (`code`, `name`) VALUES ('AR', 'Argentina');
INSERT INTO `state` (`name`, `country_id`) VALUES ('Buenos Aires', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Catamarca', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Chaco', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Chubut', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Córdoba', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Corrientes', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Entre Ríos', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Formosa', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Jujuy', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('La Pampa', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('La Rioja', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Mendoza', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Misiones', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Neuquén', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Río Negro', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Salta', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('San Juan', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('San Luis', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Santa Cruz', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Santa Fe', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Santiago del Estero', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tierra del Fuego', 12);
INSERT INTO `state` (`name`, `country_id`) VALUES ('Tucumán', 12);
